# WEBCAM

In [1]:
import cv2
import mediapipe as mp
import numpy as np
from PIL import Image

import tensorflow
from tensorflow import keras

model=keras.models.load_model(r'D:\DL_Projects\Project-DL\DLoroject_model_new.h5')

face_cascade=cv2.CascadeClassifier(r'D:\DL_Projects\Project-DL\haarcascade_frontalface_default.xml')
face_cascade



c:\Users\xiaomi\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:99: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(


< cv2.CascadeClassifier 0000020DEAFA38F0>

In [4]:

def detect_and_display_mask(frame):
        gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
        faces=face_cascade.detectMultiScale(gray,minNeighbors=6)


        for (x,y,w,h) in faces:
            face_roi=frame[y-70:y+h+60,x-70:x+w+70]

            # Print shape before resizing:
            #print(face_roi.shape) 

           
            imgre = cv2.resize(gray, (150, 150))  # Resize to 150x150:

            # Print final shape before reshaping for prediction:
            #print(imgre.shape)  # Should be (150, 150) for grayscale image

            # Reshape only for model prediction (assuming single-channel):
            img = imgre.reshape(1, 150, 150, 1)
            #print(img.shape)
             
            
            li=['without_helmet','with_helmet']

            pred = model.predict(img)      #  prediction 
            print(pred)
            ind=pred.argmax(axis=1)
            predictions=li[ind.item()]
            print(predictions)
            
            
            if predictions == "without_helmet":
                mask_message='u can continue'  
                print(mask_message)

            else: 
                mask_message = "Please remove the helmet."
                print(mask_message)

            
        # Draw bounding box (optional) and display the message on the frame
            if mask_message:
                #Code for drawing bounding box (if applicable)
                cv2.putText(frame, mask_message, (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (0, 0, 255), 2)



video=cv2.VideoCapture(0)
while True:
    success,frame=video.read()
    detect_and_display_mask(frame)

    cv2.imshow('Webcam',frame)
    if cv2.waitKey(1) & 0XFF==ord('q'):
        break
video.release()
cv2.destroyAllWindows()


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
[[1. 0.]]
without_helmet
u can continue
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step
[[1. 0.]]
without_helmet
u can continue
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
[[1. 0.]]
without_helmet
u can continue
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
[[1. 0.]]
without_helmet
u can continue
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step
[[9.999931e-01 6.943796e-06]]
without_helmet
u can continue
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
[[1. 0.]]
without_helmet
u can continue
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
[[1. 0.]]
without_helmet
u can continue
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step
[[1. 0.]]
without_helmet
u can continue
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
[[1. 0.]]
without_helmet
u can continue
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step
[[1. 0.]]
without_helmet
u can continue
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step
[[1. 0.]]
without_helmet
u can continue
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
[[1. 0.]]
without_helmet
u can continue
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
[[1. 0

In [ ]:
# gray=cv2.cvtColor(face_frame,cv2.COLOR_BGR2GRAY)
        # imgre = cv2.resize(gray, (150, 150))  # Resize to 150x150:
        # img = imgre.reshape(1, 150, 150, 1)
        # li=['without_helmet','with_helmet']

        # predictions = model.predict(img)      #  prediction 
        # ind=predictions.argmax(axis=1)
        # predictions=li[ind.item()]

        # if predictions == "without_helmet":  
        #     message='u can continue'  
        #     #st.write(mask_message)

        # elif predictions == "with_helmet": 
        #     message = "Please remove the helmet."
        #     #st.write(mask_message)


        # if message:
        #       # Code for drawing bounding box (if applicable)
        #   cv2.putText(frame, message, (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (0, 0, 255), 2)

# Image

In [11]:
newimg = cv2.imdecode(np.frombuffer(newimg, np.uint8), cv2.IMREAD_COLOR)  # Assuming color image
#img=cv2.imread(r'D:\DL_Projects\Project-DL\with_helmet_pic.jpg')
img=cv2.imread(r'D:\DL_Projects\Project-DL\without_helmet_pic.JPG')
c_img=cv2.cvtColor(img,cv2.COLOR_RGB2BGR)
c_img_gray=cv2.cvtColor(c_img,cv2.COLOR_BGR2GRAY)

faces=face_cascade.detectMultiScale(c_img_gray,minNeighbors=6)


imgre = cv2.resize(c_img_gray, (150, 150))  # Resize to 150x150:
img = imgre.reshape(1, 150, 150, 1)
li=['without_helmet','with_helmet']

predictions = model.predict(img)      #  prediction 
ind=predictions.argmax(axis=1)
predictions=li[ind.item()]

if predictions == "without_helmet":  
    message='u can continue'  
        #st.write(mask_message)
    print('without helmet')

elif predictions == "with_helmet": 
    message = "Please remove the helmet."
        #st.write(mask_message)
    print('with helmet')

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
without helmet


# Video

In [2]:
video=cv2.VideoCapture(r'D:\DL_Projects\Project-DL\6435396-uhd_3840_2160_30fps.mp4')
while True:
    success,frame=video.read()
    if not success:
        break
    gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    faces=face_cascade.detectMultiScale(gray,minNeighbors=6)
    #print(faces)
    #print(success)
    for (x,y,w,h) in faces:
        cv2.rectangle(frame,(x,y),(x+w,y+h),(0,0,255),5)



    cv2.imshow('video',frame)
    if cv2.waitKey(1) & 0XFF==ord('q'):
        break
video.release()
cv2.destroyAllWindows()

In [4]:
from moviepy.editor import VideoFileClip

# Load the video clip
clip = VideoFileClip(r'D:\DL_Projects\Project-DL\6435396-uhd_3840_2160_30fps.mp4')

# Define desired output resolution (width, height)
output_width = 800
output_height = 600

# Resize the video clip
resized_clip = clip.resize((output_width, output_height))

# Process the resized clip frame by frame (similar to the original code)
for frame in resized_clip.iter_frames():
    gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    faces=face_cascade.detectMultiScale(gray,minNeighbors=6)
    #print(faces)
    #print(success)
    for (x,y,w,h) in faces:
        cv2.rectangle(frame,(x,y),(x+w,y+h),(0,0,255),5)



    cv2.imshow('video',frame)
    if cv2.waitKey(1) & 0XFF==ord('q'):
        break

cv2.destroyAllWindows()


# Head Detection using mediapipe

In [5]:
import cv2
import mediapipe as mp
import tensorflow
from tensorflow import keras



model=keras.models.load_model(r'D:\DL_Projects\Project-DL\DLoroject_model_new.h5')

def pred_msg(frame):
  gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
  imgre = cv2.resize(gray, (150, 150))  # Resize to 150x150:
  img = imgre.reshape(1, 150, 150, 1)
  li=['without_helmet','with_helmet']

  predictions = model.predict(img)      #  prediction 
  ind=predictions.argmax(axis=1)
  predictions=li[ind.item()]

  if predictions == "without_helmet":  
    message='u can continue'  
    #st.write(mask_message)

  elif predictions == "with_helmet": 
     message = "Please remove the helmet."
      #st.write(mask_message)

  return message

## Initialize drawing utility from MediaPipe solutions

# mp_drawing = mp.solutions.drawing_utils

# # Initialize MediaPipe's pose solution
# mp_pose = mp.solutions.pose.Pose()

# Start video capture
cap = cv2.VideoCapture(0)

while cap.isOpened():
  success, image = cap.read()

  if not success:
    print("Ignoring empty camera frame.")
    continue


  # Convert image to RGB format (MediaPipe expects)
  image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
  

  # Perform pose detection
  #results = mp_pose.process(image)
  
  image = cv2.cvtColor((image), cv2.COLOR_RGB2BGR)
  msg=pred_msg(image)
  print(msg)
  
    

  # # # Display the resulting frame
  cv2.imshow('MediaPipe Pose', image)

  # Exit on 'q' key press
  if cv2.waitKey(5) & 0xFF == ord('q'):
    break

# Release resources
cap.release()
cv2.destroyAllWindows()


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step
Please remove the helmet.
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step
Please remove the helmet.
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
Please remove the helmet.
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
Please remove the helmet.
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
Please remove the helmet.
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
Please remove the helmet.
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
Please remove the helmet.
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
Please remove the helmet.
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
Please remove the helmet.
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
Please remove the helmet.
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
Please remove the helmet.
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
u can continue
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
u can continue
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
u can continue
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
u can continue
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
u can continue
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28m